name: Main

on: 
  pull_request:
    branches:
      - master

env:
  RUST_BACKTRACE: 1

jobs:
  build_test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install nightly Rust and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          target: wasm32-unknown-unknown

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Run tests
        run: cargo make --no-workspace verify_only
        working-directory: ./
