name: Main

on:
  push:
    branches:
      - stable

env:
  RUST_BACKTRACE: 1

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      
      - name: Release test_zia
        run: cargo package && cargo publish --token ${{secrets.CRATES_TOKEN}}
        working-directory: ./test_zia

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      
      - name: Release zia
        run: cargo package && cargo publish --token ${{secrets.CRATES_TOKEN}}
        working-directory: ./zia

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Release izia
        run: cargo package && cargo publish --token ${{secrets.CRATES_TOKEN}}
        working-directory: ./izia
