name: Website

on: push

env:
  RUST_BACKTRACE: 1

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Install node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install nightly Rust and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-07-07
          components: rustfmt

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
        with:
          version: "0.35.1"

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: "v0.13.0"

      - name: Install Node dependencies
        run: yarn
        working-directory: ./zia-lang.org

      - name: Build
        run: yarn build:release
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        working-directory: ./zia-lang.org

      - name: Install Netlify CLI
        if: github.ref == 'refs/heads/master'
        run: sudo npm install netlify-cli -g

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
        run: sudo netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./zia-lang.org/dist
